# Generated by Django 4.1.1 on 2022-12-11 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tiempo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank='', upload_to='medallas')),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaReto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('image', models.ImageField(blank='', upload_to='preguntas')),
                ('respuestaCorrecta', models.CharField(max_length=200)),
                ('respuestaIncorrecta1', models.CharField(max_length=200)),
                ('respuestaIncorrecta2', models.CharField(max_length=200)),
                ('respuestaIncorrecta3', models.CharField(max_length=200)),
                ('puntos', models.IntegerField(default=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuestaCorrecta', models.CharField(max_length=200)),
                ('respuestaIncorrecta1', models.CharField(max_length=200)),
                ('respuestaIncorrecta2', models.CharField(max_length=200)),
                ('respuestaIncorrecta3', models.CharField(max_length=200)),
                ('puntos', models.IntegerField(default=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tema')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('birthday_date', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank='', default='profiles/icono foto.png', upload_to='profiles')),
                ('puntos', models.IntegerField(default=0)),
                ('customer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
